{% set name = "IOHexperimenter" %}
{% set version = "0.2.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/IOHexperimenter-{{ version }}.tar.gz
  sha256: 81e0dcdc6b966ebdb53f990d73b8cd024fe13f75c871189b6f7364f93345b6b5

build:
  number: 0
  skip: true  # [py2k]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler("cxx") }}
  host:
    - pip
    - python
  run:
    - numpy
    - python
    - setuptools
test:
  imports:
    - IOHexperimenter
    - tests

about:
  home: https://github.com/IOHprofiler/IOHexperimenter
  summary: The experimenter for Iterative Optimization Heuristic
  license: GPL-3.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - JennaLipscomb
    - oblute
