{% set name = "IOHexperimenter" %}
{% set version = "0.2.9.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/IOHexperimenter-{{ version }}.tar.gz
  sha256: 51315f4beae84361e332ed1bbb1adf9004162e208efd95e192a87d6d1465e847

build:
  number: 5
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
  host:
    - pip
    - python
    - setuptools
  run:
    - numpy
    - python
    - setuptools
test:
  imports:
    - IOHexperimenter
    - tests

about:
  home: https://github.com/IOHprofiler/IOHexperimenter
  summary: The experimenter for Iterative Optimization Heuristic
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - mxr-conda
    - JennaLipscomb
    - oblute
