{% set name = "IOHexperimenter" %}
{% set version = "0.2.9.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/IOHexperimenter-{{ version }}.tar.gz
  sha256: 51315f4beae84361e332ed1bbb1adf9004162e208efd95e192a87d6d1465e847

build:
  number: 2
  skip: true  # [py2k]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler("cxx") }}
  host:
    - pip
    - python
  run:
    - numpy
    - python
    - setuptools
test:
  imports:
    - IOHexperimenter
    - tests

about:
  home: https://github.com/IOHprofiler/IOHexperimenter
  summary: The experimenter for Iterative Optimization Heuristic
  license: GPL-3.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - mxr-conda
    - JennaLipscomb
    - oblute
